authapp/urls.py
import authapp.views as authapp
from django.conf.urls import url

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'^edit/', authapp.edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contacts/', mainapp.contacts, name='contacts'),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url

import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [
    url('^$', mainapp.products, name='index'),
    url(r'^(?P<pk>\d+)/$', mainapp.products, name='category')
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='age')

mainapp/models.py
from django.db import models


class ProductCategory (models.Model):
    name = models.CharField(verbose_name='Category', max_length=128, unique=True)
    description = models.TextField(verbose_name='Description', blank=True)

    def __str__(self):
        return self.name


class Product (models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Name', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='Short description', max_length=60, blank=True)
    description = models.TextField(verbose_name='Description', blank=True)
    price = models.DecimalField(verbose_name='Price', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='Quantity', default=0)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)

mainapp/views.py
from django.shortcuts import render
from .models import Product, ProductCategory


def main(request):
    return render(request, 'mainapp/index.html')


def products(request, pk=None):
    title = 'Products'

    products_list = Product.objects.all()[:4]

    content = {'title': title, 'products': products_list}
    return render(request, 'mainapp/products.html', content)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru-ru">
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main' %}" class="">
            на главную
        </a>
    </button>
    <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}
    {% endblock %}
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
        <div class="footer padding-site">
            <div class="footer-top">
                <div class="contact-us">
                    <h4 class="footer-top-h4">Contact Us</h4>
                    <p class="footer-top-p">132A Bridge Road Richmond VIC Australia.</p>
                    <p class="footer-top-p">Talk to us on 1300 132
                    info@interior.com</p>
                </div>
                <div class="useful-information">
                    <h4 class="footer-top-h4">Useful Information</h4>
                    <div class="useful-links">
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Sales terms</a>
                            <a href="#" class="useful-link">Customer care</a>
                            <a href="#" class="useful-link">Delivery</a>
                        </div>
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Architect accounts</a>
                            <a href="#" class="useful-link">Careers</a>
                            <a href="#" class="useful-link">Exchanges &amp; returns</a>
                        </div>
                    </div>
                </div>
                <div class="stay-in-touch">
                    <h4 class="footer-top-h4">Let’s Stay in Touch!</h4>
                    <p class="footer-top-p">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                    <form action="">
                        <input type="email" placeholder="your email address">
                        <button type="submit"><img src="{% static 'img/submit.png' %}" alt="Submit"></button>
                    </form>
                </div>
            </div>
            <div class="footer-bottom">
                <span class="copyright">&copy; Copyright - INTERIOR 2016. All Rights Reserved.</span>
                <span class=""><img src="/static/img/social-links.png" alt="Social links"></span>
                <span>
                    <a href="#" class="footer-bottom-link">Terms &amp; Conditions</a>
                    <span> &frasl; </span>
                    <a href="#" class="footer-bottom-link">Privacy policy &amp; Cookies</a>
                </span>
            </div>
        </div>
    </div>
    {% block js %}
    {% endblock %}
</body>

</html>

mainapp/templates/mainapp/contacts.html
<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <div class="container">
        <header class="padding-site">
            <div class="header">
                <a class="logo" href="#"><img src="/static/img/logo.svg" alt="logo"></a>
                <ul class="menu">
                    <li><a href="% url 'index' %}" class="menu-link">HOME </a></li>
                    <li><a href="#" class="menu-link">PRODUCTS </a></li>
                    <li><a href="#" class="menu-link">HISTORY </a></li>
                    <li><a href="#" class="menu-link">SHOWROOM</a></li>
                    <li><a href="% url 'contacts' %}" class="menu-link-active menu-link">CONTACT</a></li>
                    <li><a href="#" class="menu-link"><img src="/static/img/search.svg" alt="search"></a></li>
                </ul>
            </div>
            <h2 class="header-h2">Contact Us</h2>
        </header>
        <div class="location padding-site">
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
        </div>
        <footer class="footer padding-site">
            <div class="footer-top">
                <div class="contact-us">
                    <h4 class="footer-top-h4">Contact Us</h4>
                    <p class="footer-top-p">132A Bridge Road Richmond VIC Australia.</p>
                    <p class="footer-top-p">Talk to us on 1300 132
                    info@interior.com</p>
                </div>
                <div class="useful-information">
                    <h4 class="footer-top-h4">Useful Information</h4>
                    <div class="useful-links">
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Sales terms</a>
                            <a href="#" class="useful-link">Customer care</a>
                            <a href="#" class="useful-link">Delivery</a>
                        </div>
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Architect accounts</a>
                            <a href="#" class="useful-link">Careers</a>
                            <a href="#" class="useful-link">Exchanges &amp; returns</a>
                        </div>
                    </div>
                </div>
                <div class="stay-in-touch">
                    <h4 class="footer-top-h4">Let’s Stay in Touch!</h4>
                    <p class="footer-top-p">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                    <form action="">
                        <input type="email" placeholder="your email address">
                        <button type="submit"><img src="/static/img/submit.png" alt="Submit"></button>
                    </form>
                </div>
            </div>
            <div class="footer-bottom">
                <span class="copyright">&copy; Copyright - INTERIOR 2016. All Rights Reserved.</span>
                <span class=""><img src="/static/img/social-links.png" alt="Social links"></span>
                <span>
                    <a href="#" class="footer-bottom-link">Terms &amp; Conditions</a>
                    <span> &frasl; </span>
                    <a href="#" class="footer-bottom-link">Privacy policy &amp; Cookies</a>
                </span>
            </div>
        </footer>
    </div>
</body>
</html>
-->

{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Contacts</title>
{% endblock %}

{% block content %}
    <header class="padding-site">
        <div class="header">
            {% include 'mainapp/include/inc_menu.html' %}
        </div>
        <h2 class="header-h2">Contact Us</h2>
    </header>
    <div class="location padding-site">
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="location-item">
                <div class="location-img"><img src="/static/img/location-img.png" alt="Location"></div>
                <h4 class="location-h4">California</h4>
                <p class="location-p">Phone:<br><b>1900 - 1234 -5678</b></p>
                <p class="location-p">Email:<br><b>info@interior.com</b></p>
                <p class="location-p">Address:<br>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
        </div>
{% endblock %}


mainapp/templates/mainapp/include/inc_menu.html
{% if user.is_authenticated %}
<li>
    <a href="{% url 'auth:edit' %}">
        {{ user.first_name|default:'Пользователь' }}
    </a>
</li>
{% endif %}
<li>
    {% if user.is_authenticated %}
      <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
        <a href="{% url 'auth:login' %}">войти</a> or <a href="{% url 'auth:register' %}">Register</a>
    {% endif %}
</li>
<a class="logo" href="#"><img src="/static/img/logo.svg" alt="logo"></a>
<ul class="menu">
    <li><a href="{% url 'main' %}" class="menu-link">HOME </a></li>
    <li><a href="{% url 'products:index' %}" class="menu-link">PRODUCTS </a></li>
    <li><a href="#" class="menu-link">HISTORY </a></li>
    <li><a href="#" class="menu-link">SHOWROOM</a></li>
    <li><a href="{% url 'contacts' %}" class="menu-link">CONTACT</a></li>
    <li><a href="#" class="menu-link"><img src="/static/img/search.svg" alt="search"></a></li>
</ul>

mainapp/templates/mainapp/index.html
<!--<!DOCTYPE html>
% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="% static 'css/style.css' %}">
</head>

<body>

        <div class="footer padding-site">
            <div class="footer-top">
                <div class="contact-us">
                    <h4 class="footer-top-h4">Contact Us</h4>
                    <p class="footer-top-p">132A Bridge Road Richmond VIC Australia.</p>
                    <p class="footer-top-p">Talk to us on 1300 132
                    info@interior.com</p>
                </div>
                <div class="useful-information">
                    <h4 class="footer-top-h4">Useful Information</h4>
                    <div class="useful-links">
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Sales terms</a>
                            <a href="#" class="useful-link">Customer care</a>
                            <a href="#" class="useful-link">Delivery</a>
                        </div>
                        <div class="useful-links-column">
                            <a href="#" class="useful-link">Architect accounts</a>
                            <a href="#" class="useful-link">Careers</a>
                            <a href="#" class="useful-link">Exchanges &amp; returns</a>
                        </div>
                    </div>
                </div>
                <div class="stay-in-touch">
                    <h4 class="footer-top-h4">Let’s Stay in Touch!</h4>
                    <p class="footer-top-p">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                    <form action="">
                        <input type="email" placeholder="your email address">
                        <button type="submit"><img src="/static/img/submit.png" alt="Submit"></button>
                    </form>
                </div>
            </div>
            <div class="footer-bottom">
                <span class="copyright">&copy; Copyright - INTERIOR 2016. All Rights Reserved.</span>
                <span class=""><img src="/static/img/social-links.png" alt="Social links"></span>
                <span>
                    <a href="#" class="footer-bottom-link">Terms &amp; Conditions</a>
                    <span> &frasl; </span>
                    <a href="#" class="footer-bottom-link">Privacy policy &amp; Cookies</a>
                </span>
            </div>
        </div>
    </div>
</body>

</html>
-->

{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content %}
    <div class="slider padding-site">
            <div class="header">
                {% include 'mainapp/include/inc_menu.html' %}
            </div>
            <div class="slider-text">
                <h4 class="slider-h4">TRENDING</h4>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-p">
                    Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
                </p>
                <a href="#" class="button">order us &gt;</a>
            </div>
            <div class="slider-pagination">
                <a href="" class="circle"></a>
                <a href="" class="circle circle-active"></a>
                <a href="" class="circle"></a>
            </div>
        </div>
    <div class="featured-new padding-site">
            <div class="product-header">
                <a href="#" class="featured-link active-featured-link">Featured</a>
                <a href="#" class="featured-link">New</a>
                <a href="#" class="explore-all">explore all &gt;</a>
            </div>
            <div class="product-container">
                <div class="product" style="background-image: url(/static/img/product-1.jpg)">
                    <div class="product-text">
                        <a href="#" class="product-button"></a>
                        <h4 class="product-h4">Fishnet Chair</h4>
                        <p class="product-p">Seat and back with upholstery made of cold cure foam</p>
                    </div>
                </div>
                <div class="product" style="background-image: url(/static/img/product-2.jpg)">
                    <div class="product-text">
                        <a href="#" class="product-button"></a>
                        <h4 class="product-h4">Fishnet Chair</h4>
                        <p class="product-p">Seat and back with upholstery made of cold cure foam</p>
                    </div>
                </div>
                <div class="product" style="background-image: url(/static/img/product-3.jpg)">
                    <div class="product-text">
                        <a href="#" class="product-button"></a>
                        <h4 class="product-h4">Fishnet Chair</h4>
                        <p class="product-p">Seat and back with upholstery made of cold cure foam</p>
                    </div>
                </div>
                <div class="product" style="background-image: url(/static/img/product-4.jpg)">
                    <div class="product-text">
                        <a href="#" class="product-button"></a>
                        <h4 class="product-h4">Fishnet Chair</h4>
                        <p class="product-p">Seat and back with upholstery made of cold cure foam</p>
                    </div>
                </div>
            </div>
        </div>
    <div class="promo">
            <div class="promo-item item1">
                <p class="exclusive">exclusive</p>
                <h4 class="promo-h4">Fishnet Chair</h4>
                <p class="promo-item-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                <a href="#" class="button">order us &gt;</a>
            </div>
            <div class="promo-item item2">
                <p class="exclusive">exclusive</p>
                <h4 class="promo-h4">Fishnet Chair</h4>
                <p class="promo-item-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt</p>
                <a href="#" class="button">order us &gt;</a>
            </div>
        </div>
    <div class="trending-products padding-site">
            <div class="trending-product-header">
                <h3 class="trending-product-h3">Trending Products</h3>
                <a href="#" class="explore-all">explore all &gt;</a>
            </div>
            <div class="trending-product-container">
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-11.jpg" alt="Product">
                </a>
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-21.jpg" alt="Product">
                </a>
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-31.jpg" alt="Product">
                </a>
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-41.jpg" alt="Product">
                </a>
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-5.jpg" alt="Product">
                </a>
                <a href="#" class="trending-product-item">
                    <img src="/static/img/product-6.jpg" alt="Product">
                </a>
            </div>
        </div>
    <div class="hot-deals padding-site">
            <div class="slider-text">
                <h4 class="slider-h4 hot-deal-h4">Hot deal</h4>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-p">
                    Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.
                </p>
                <a href="#" class="button">order us &gt;</a>
            </div>
            <div class="slider-pagination">
                <a href="" class="circle"></a>
                <a href="" class="circle circle-active"></a>
                <a href="" class="circle"></a>
            </div>
        </div>
    <div class="exclusive padding-site">
            <div class="exclusive-product big">
                <div class="slider-text">
                <h4 class="slider-h4 exclusive-h4">exclusive</h4>
                <h2 class="slider-h2 exclusive-h2">Fishnet Chair</h2>
                <p class="slider-p exclusive-p">
                    Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.
                </p>
                <a href="#" class="button">order us &gt;</a>
            </div>
            </div>
            <div class="small">
                <div class="exclusive-product"><img src="../../../static/img/product-2-sm.jpg" alt="Exclusive product"></div>
                <div class="exclusive-product"><img src="../../../static/img/product-3-sm.jpg" alt="Exclusive product"></div>
                <div class="exclusive-product"><img src="../../../static/img/product-4-sm.jpg" alt="Exclusive product"></div>
                <div class="exclusive-product"><img src="../../../static/img/product-5-sm.jpg" alt="Exclusive product"></div>
            </div>
        </div>
    <div class="mobile-app padding-site">
            <h4 class="mobile-app-h4">mobile app</h4>
            <h2 class="mobile-app-h2">Find. Follow. Favorite.</h2>
            <p class="mobile-app-p">Save your favorites and share your style.</p>
            <div class="mobile-app-links">
                <a href="#"><img src="/static/img/app-store.jpg" alt="AppStore"></a>
                <a href="#"><img src="/static/img/google-play.jpg" alt="Google Play"></a>
            </div>
        </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}

{% block title %}
    <title>Products</title>
{% endblock %}

{% block content %}
    <div class="header padding-site">
        {% include 'mainapp/include/inc_menu.html' %}
    </div>
    <div class="padding-site">
        {% for product in products %}
            <li>{{ product.name }} {{ product.category.name }}</li>
        {% endfor %}
    </div>
{% endblock %}